services:
  cpu-emitter-1:
    image: ghcr.io/heig-lherman/dai-pw03
    command:
      - node
      - -m
      - CPU
      - -H
      - PC-1
  cpu-emitter-2:
    image: ghcr.io/heig-lherman/dai-pw03
    command:
      - node
      - -m
      - CPU
      - -H
      - PC-2
  ram-emitter-1:
    image: ghcr.io/heig-lherman/dai-pw03
    command:
      - node
      - -m
      - RAM
      - -H
      - PC-1
  ram-emitter-2:
    image: ghcr.io/heig-lherman/dai-pw03
    command:
      - node
      - -m
      - RAM
      - -H
      - PC-3
  dsk-emitter-1:
    image: ghcr.io/heig-lherman/dai-pw03
    command:
      - node
      - -m
      - DSK
      - -H
      - PC-3
  aggregator:
    image: ghcr.io/heig-lherman/dai-pw03
    command:
      - aggregator
    ports:
      - 6343:6343/udp
    depends_on:
      - cpu-emitter-1
      - cpu-emitter-2
      - ram-emitter-1
      - ram-emitter-2
      - dsk-emitter-1
